/**:
  ros__parameters: #SOLATI
    wheel_radius: 0.355 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.235 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.67 # between front wheel center and rear wheel center
    wheel_tread: 1.718 # between left wheel center and right wheel center
    front_overhang: 0.99 # between front wheel center and vehicle front
    rear_overhang: 1.535 # between rear wheel center and vehicle rear
    left_overhang: 0.4 # between left wheel center and vehicle left
    right_overhang: 0.4 # between right wheel center and vehicle right
    vehicle_height: 2.485 
    max_steer_angle: 0.58 # [rad]